// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Saveフォルダ標準化","status":true,"description":"Saveフォルダ標準化プラグイン","parameters":{}},
{"name":"KNS_MessageExport","status":false,"description":"[ver.1.0.0(2022/3/23)]exports texts in events and database.","parameters":{}},
{"name":"KNS_MessageImport","status":false,"description":"[ver.1.0.0(2022/3/23)]Merges .txt files as .json database exported by KNS_MessageExport","parameters":{}},
{"name":"ReplaceFileName","status":false,"description":"画像、音声、動画読み込み時、指定された名前を任意の名前に置き換えて読み込むようにします。","parameters":{}},
{"name":"YEP_KeyboardConfig","status":true,"description":"v1.04 Allows players to adjust their button configuration\nfor keyboards.","parameters":{"---General---":"","Command Name":"Keyboard Config","Button Events":"1 2 3","Button Events List":"[]","---Help Text---":"","Key Help":"Change the configuration of this key?","Default Layout":"Default Keyboard Layout","Default Help":"Reverts your keyboard setting to the default setup.","WASD Layout":"WASD Movement Layout","WASD Help":"Changes your keyboard to WASD movement.","Finish Config":"Finish Configuration","Finish Help":"Are you done configuring your keyboard?","Assigned Color":"21","Action Color":"4","Clear Text":"Clear","---Key Names---":"","OK Key":"OK","OK Text":"OK / Talk","Escape Key":"X","Escape Text":"Cancel / Menu","Cancel Key":"Cancel","Cancel Text":"Cancel","Menu Key":"Menu","Menu Text":"Menu","Shift Key":"Dash","Shift Text":"Dash","PageUp Key":"PgUp","PageUp Text":"Page Up","PageDown Key":"PgDn","PageDown Text":"Page Down","Left Key":"◄","Left Text":"Move ◄ Left","Up Key":"▲","Up Text":"Move ▲ Up","Right Key":"►","Right Text":"Move ► Right","Down Key":"▼","Down Text":"Move ▼ Down"}}
];
